name: Docker Image CI

on:
  pull_request:
    branches: 
      - develop
  push:
      branches: 
        - develop  

jobs:
   
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: sonar-scanner
      run: docker run -e SONAR_HOST_URL=https://sonar.openbsl.ru -it -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli
