name: Docker Image CI

on:
  pull_request:
    branches: 
      - develop
  push:
      branches: 
        - develop  

jobs:
   
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: sonar-scanner
      run: docker run -e SONAR_PROJECT_BASE_DIR=/home/runner/work/vanessa-automation/vanessa-automation -e SONAR_USER_HOME=/home/runner/work/vanessa-automation/vanessa-automation/.sonar -v "/home/my_user/.sonar:/home/runner/work/vanessa-automation/vanessa-automation/.sonar" -e SONAR_HOST_URL=https://sonar.openbsl.ru -v "/home/runner/work/vanessa-automation/vanessa-automation:/usr/src" sonarsource/sonar-scanner-cli
